apiVersion: v1
kind: Service
metadata:
  name: employees
  labels:
    name: employees
spec:
 type: NodePort
 ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    name: employees