apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees
  labels:
    app: employees
spec:
  selector:
    matchLabels:
      app: employees
  replicas: 1
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: employees
        image: 660700579747.dkr.ecr.us-east-1.amazonaws.com/assignment2ecr:v0.1nodeapp
    env:
    - name: DBHOST
      value: "10.244.0.5"
    - name: DBPWD
      value: "pw"
    - name: DBPORT
      value: 3306
    - name: DBUSER
      value: "root"