apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
  - name: mysql
    image: 660700579747.dkr.ecr.us-east-1.amazonaws.com/assignment2ecr:v1.1mysql
    port:
    - containerPort: 3306
    env:
    - name : DBPWD
      value : "pw"
    - name : DBUSER
      value : "root"
    - name : MYSQL_ROOT_PASSWORD
      value : "pw"
